SMELL_CATALOG = {
    "Magic Number": {
        "category": "implementation",
        "group": "literals_constants",
        "primary_strategy": "replace_magic_number_with_constant",
        "fallback_strategies": ["replace_primitive_with_value_object"],
        "validation_level": "syntax",
        "priority": 1,
    },
    "Blob (God Class)": {
        "category": "design",
        "group": "size_responsibility",
        "primary_strategy": "extract_class",
        "fallback_strategies": ["move_method", "move_field", "split_responsibilities"],
        "validation_level": "structural",
        "priority": 1,
    },
    "Data Class": {
        "category": "design",
        "group": "data_behavior",
        "primary_strategy": "encapsulate_field",
        "fallback_strategies": ["move_method", "extract_class"],
        "validation_level": "structural",
        "priority": 2,
    },
    "Long Method": {
        "category": "design",
        "group": "size_complexity",
        "primary_strategy": "extract_method",
        "fallback_strategies": ["decompose_conditional"],
        "validation_level": "syntax",
        "priority": 1,
    },
    "Feature Envy": {
        "category": "design",
        "group": "responsibility_placement",
        "primary_strategy": "move_method",
        "fallback_strategies": ["extract_method", "reduce_coupling"],
        "validation_level": "structural",
        "priority": 1,
    },
    "Shotgun Surgery": {
        "category": "design",
        "group": "change_prevention",
        "primary_strategy": "extract_class",
        "fallback_strategies": ["move_method", "split_responsibilities"],
        "validation_level": "structural",
        "priority": 2,
    },
    "Divergent Change": {
        "category": "design",
        "group": "change_prevention",
        "primary_strategy": "split_responsibilities",
        "fallback_strategies": ["extract_class"],
        "validation_level": "structural",
        "priority": 2,
    },
    "Lazy Class": {
        "category": "design",
        "group": "abstraction",
        "primary_strategy": "inline_method_or_class",
        "fallback_strategies": ["remove_dead_code"],
        "validation_level": "structural",
        "priority": 3,
    },
    "Refused Bequest": {
        "category": "design",
        "group": "inheritance",
        "primary_strategy": "replace_inheritance_with_delegation",
        "fallback_strategies": ["split_responsibilities"],
        "validation_level": "structural",
        "priority": 2,
    },
    "Middle Man": {
        "category": "design",
        "group": "responsibility_placement",
        "primary_strategy": "inline_method_or_class",
        "fallback_strategies": ["move_method"],
        "validation_level": "structural",
        "priority": 3,
    },
    "Message Chains": {
        "category": "design",
        "group": "coupling_navigation",
        "primary_strategy": "move_method",
        "fallback_strategies": ["reduce_coupling"],
        "validation_level": "structural",
        "priority": 2,
    },
    "Long Parameter List": {
        "category": "shared",
        "group": "data_parameters",
        "primary_strategy": "introduce_parameter_object",
        "fallback_strategies": ["replace_primitive_with_value_object"],
        "validation_level": "syntax",
        "priority": 1,
    },
    "Primitive Obsession": {
        "category": "design",
        "group": "data_parameters",
        "primary_strategy": "replace_primitive_with_value_object",
        "fallback_strategies": ["introduce_parameter_object"],
        "validation_level": "structural",
        "priority": 2,
    },
    "Switch Statements": {
        "category": "design",
        "group": "control_flow",
        "primary_strategy": "replace_conditional_with_polymorphism",
        "fallback_strategies": ["decompose_conditional"],
        "validation_level": "structural",
        "priority": 2,
    },
    "Speculative Generality": {
        "category": "design",
        "group": "abstraction",
        "primary_strategy": "inline_method_or_class",
        "fallback_strategies": ["remove_dead_code"],
        "validation_level": "structural",
        "priority": 3,
    },
    "Temporary Field": {
        "category": "shared",
        "group": "state",
        "primary_strategy": "extract_class",
        "fallback_strategies": ["split_responsibilities"],
        "validation_level": "structural",
        "priority": 2,
    },
    "Data Clumps": {
        "category": "design",
        "group": "data_parameters",
        "primary_strategy": "introduce_parameter_object",
        "fallback_strategies": ["extract_class"],
        "validation_level": "syntax",
        "priority": 1,
    },
    "Inappropriate Intimacy": {
        "category": "design",
        "group": "coupling_navigation",
        "primary_strategy": "move_method",
        "fallback_strategies": ["move_field", "reduce_coupling"],
        "validation_level": "structural",
        "priority": 2,
    },
    "Duplicate Code": {
        "category": "shared",
        "group": "duplication",
        "primary_strategy": "extract_method",
        "fallback_strategies": ["extract_class"],
        "validation_level": "syntax",
        "priority": 1,
    },
    "Complex Conditional": {
        "category": "design",
        "group": "control_flow",
        "primary_strategy": "decompose_conditional",
        "fallback_strategies": ["replace_conditional_with_polymorphism"],
        "validation_level": "syntax",
        "priority": 1,
    },
    "Dead Code": {
        "category": "implementation",
        "group": "redundancy",
        "primary_strategy": "remove_dead_code",
        "fallback_strategies": [],
        "validation_level": "syntax",
        "priority": 1,
    },
    "Complex Method": {
        "category": "implementation",
        "group": "size_complexity",
        "primary_strategy": "extract_method",
        "fallback_strategies": ["decompose_conditional"],
        "validation_level": "syntax",
        "priority": 1,
    },
    "Excessive Class Length": {
        "category": "implementation",
        "group": "size_responsibility",
        "primary_strategy": "extract_class",
        "fallback_strategies": ["split_responsibilities"],
        "validation_level": "structural",
        "priority": 2,
    },
    "Excessive Method Length": {
        "category": "implementation",
        "group": "size_complexity",
        "primary_strategy": "extract_method",
        "fallback_strategies": ["decompose_conditional"],
        "validation_level": "syntax",
        "priority": 1,
    },
    "Excessive Return Statements": {
        "category": "implementation",
        "group": "control_flow",
        "primary_strategy": "decompose_conditional",
        "fallback_strategies": ["extract_method"],
        "validation_level": "syntax",
        "priority": 2,
    },
    "Excessive Coupling": {
        "category": "implementation",
        "group": "coupling_navigation",
        "primary_strategy": "reduce_coupling",
        "fallback_strategies": ["move_method", "extract_class"],
        "validation_level": "structural",
        "priority": 2,
    },
    "Excessive Public Fields": {
        "category": "implementation",
        "group": "state",
        "primary_strategy": "encapsulate_field",
        "fallback_strategies": ["extract_class"],
        "validation_level": "syntax",
        "priority": 1,
    },
    "Excessive Static Fields": {
        "category": "implementation",
        "group": "state",
        "primary_strategy": "encapsulate_field",
        "fallback_strategies": ["extract_class", "split_responsibilities"],
        "validation_level": "structural",
        "priority": 2,
    },
}
